Delete message from chat
stakwork/sphinx-kotlin pull request #199
Opened 2021-07-09 02:26 UTC by kngako

https://github.com/stakwork/sphinx-kotlin/issues/196

2021-07-09 13:01 UTC, kevkevinpal commented on sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
> +                            // TODO: Give user some information about failure maybe?
Might be able to do some sort of modal or something here indicating failure?

2021-07-09 13:04 UTC, kevkevinpal commented
Also not sure if we should be merging to the develop branch or not

2021-07-09 14:19 UTC, tomastiminskas commented
@kngako a few changes required:
- Make message options menu a bit wider since the "Delete message" text is pretty close to the right edge
- Get the response of the deleteMessage endpoint on `ChatViewModel` and use `ChatSideEffect.Notify` to show an error toast to the user
- On `DashboardChat` -> `getMessageText` check for deleted status and show "Message deleted" instead of message text. That is the text that shows the last message on Dashboard rows

2021-07-09 18:18 UTC, kngako commented
Thanks for the feedback @kevkevinpal and @tomastiminskas. I've applied the changes and updated the pull request to use develop as the base.

2021-07-12 12:48 UTC, tomastiminskas commented
@kngako last changes:
- "message deleted" should be replaced by "Message deleted"
- On the `getMessageText()` of `DashboardChat`, the check for deleted status shouldn't be inside the Message type statement. Since it should apply to other messages types like attachments. It should be placed after `messageDecryptionError` and before `type.isMessage()`

Once that's done I think we can merge this.

2021-07-12 13:43 UTC, kngako commented
@tomastiminskas cool. I just made the change.

2021-07-12 19:11 UTC, 05nelsonm requested changes

2021-07-12 19:11 UTC, 05nelsonm commented on sphinx/screens/chats/chat-common/chat-common/src/main/java/chat/sphinx/chat_common/ui/ChatFragment.kt
> -                                // TODO: Implement
Should always prefer to utilize viewModelScope in possible, as cancellation of the lifecycleScope will cancel the suspend function being called, thus not handling the returned value.

```kotlin
// from screen
viewModel.deleteMessage(holderState.message)

// from viewmodel
fun deleteMessage(message: Message) {
    viewModelScope.launch(mainImmediate) {
        when (messageRepository.deleteMessage(message)) {
            // ......
        }
    }
}
```

2021-07-13 08:16 UTC, merged