Row link previews
stakwork/sphinx-kotlin pull request #261
Opened 2021-08-05 19:26 UTC by kngako

on contact, tribe, and url links contained in messages.

2021-08-09 15:41 UTC, 05nelsonm requested changes
Structure of this feature needs some work, particularly how data is loaded to the screen.

General structure of the application is one of uni-directional data flow whereby stateful objects are created via data retrieval from a source which are observed and loaded to the UI components.

The current implementation results in network requests going out every time the Holder is bound to the screen in order to retrieve the data. That needs to be hoisted up to the Stateful object (`MessageHolderViewState`). This will allow for the data retrieval to happen via the `viewModelScope` w/o interruption, while being observed and loaded under a different scope (onStartStopSupervisor.scope), which in turn enables the cancellation of loading the data to the screen upon scrolling, but the data retrieval/processing itself is uninterrupted (unless the user navigates back, clearing the `ViewModel`)

In order to achieve this, it would fair far better to create an entirely separate concept/feature component that can be injected via the `ViewModel` constructor whereby a method can simply be called using the URL of the message, and all the necessary data (title, favicon, description, etc) is returned and then set on that `MessageHolderViewState`. This would require an additional callback into the `ViewModel` being set on that `ViewState`, which is fine because contextually the ViewModel persists uninterrupted unless the user navigates back (in which scopes are correctly cleaned up and cancelled).

Utilization of Kotlin's `Mutex` class while wrapping the method within the `MessageHolderViewState` which will be called from the UI when the `MessageHolder` is populated would ensure that the data is retrieved once, set to the stateful object, and then even if the user scrolls away and then back to that message, the data will immediately load instead of being parsed again.

There are other elements that could use improvement, particularly with regard to the parsing of the data. I'm looking more into `jsoup` to see if an input stream can be utilized instead of a String, as this can cause significant memory related issues (as noted in my comment on `NetworkRelayCallImpl`).

2021-08-09 17:03 UTC, kngako commented
How suitable would it be to populate the previewable data (title, image, description and the likes) when a message is received/stored into the database? Assuming this will still maintain the uni-directional data flow? And move most of the logic to parts/threads of the code that behave in a similar?

2021-08-09 17:19 UTC, 05nelsonm commented
> How suitable would it be to populate the previewable data (title, image, description and the likes) when a message is received/stored into the database? Assuming this will still maintain the uni-directional data flow? And move most of the logic to parts/threads of the code that behave in a similar?

I like the idea, but I believe it'd be an unnecessary use of the User's disk space (how likely will they load a 2 month old message?).

Taking a note from COIL, I think the most optimal solution would be caching the data to memory utilizing a static map with the key being that of the url. That map value would be a custom class where by synchronous execution can be had utilizing another `Mutex` so that handling multiple calls for the same url would only retrieve the data once which gets set to the map, fulfilling multiple requests with a SSOT from the map.

I'm working on the concept/feature module right now for this functionality so we can move the majority of this code up a level.

2021-08-11 20:54 UTC, 05nelsonm approved these changes

2021-08-11 20:59 UTC, merged