Subscriptions
stakwork/sphinx-kotlin pull request #301
Opened 2021-08-31 17:03 UTC by kngako

https://github.com/stakwork/sphinx-kotlin/issues/296

2021-09-01 22:19 UTC, tomastiminskas commented
@05nelsonm this PR as the #302 includes a db migration with name 2.sqm so once #302 is approved and merged, we should merge develop into this branch and rename the migration to 3.sqm

2021-09-02 15:45 UTC, 05nelsonm requested changes

2021-09-02 15:45 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionFragment.kt
> +    override suspend fun onViewStateFlowCollect(viewState: SubscriptionViewState) {
The primary purpose of a `ViewState` is to describe the state of the view, not only hold the data and then based off of the data, set the view. As it looks now, one cannot look at the xml layout, and the view state, and decipher what each view's state is. All of the logic is in the renderer when it should belong in the ViewModel (or when the view's state is instantiated for immutability/encapsulation purposes).

2021-09-02 15:45 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionViewModel.kt
> +                                    )
unnecessary. Remove.

success case returns a paused, updated subscription object and can be set w/o need to re-instantiate a `Subscription` object.

2021-09-02 15:45 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionViewModel.kt
> +                                    )
unnecessary. Remove and use returned sub.

2021-09-02 15:45 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionViewState.kt
> +        val subscription: Subscription
subscription data does not describe the view's state. move all logic to view model.

2021-09-02 15:45 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/widgets/SphinxRadioGroup.kt
> +) : ConstraintLayout(context, attrs, defStyleAttr, defStyleRes) {
Remove Use of `SphinxRadioGroup` custom class.

Custom views such as this:
 - Lock things to the Android platform
 - Does not promote extensibility
 - Needs testing
 - Couples the View and State

This functionality could easily be achieved using the rest of the application's already implemented MVI pattern (`ViewState`) to describe the state of the view, and update it upon reaction to events (such as when a user clicks 1 check box, the rest of them on the view state would change to `checked = false`). Utilizing `ViewState` allows for use of primitive views (`ConstraintLayout`, `CheckBox`, `TextView`) that are already very well tested such that we can de-couple the state from the View by simply rendering things based off of what is described.

Making views and fragments as "dumb" as possible is the primary goal.

2021-09-02 16:54 UTC, tomastiminskas commented on sphinx/application/data/features/feature-repository/src/main/java/chat/sphinx/feature_repository/SphinxRepository.kt
> +                .mapToOneOrNull(io)
Was changed and renamed to return last active subscription by contact id

2021-09-02 17:09 UTC, 05nelsonm requested changes

2021-09-02 17:09 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionViewModel.kt
> +            subscriptionRepository.getActiveSubscriptionByContactId(ContactId(args.argContactId)).distinctUntilChanged().collect { subscription ->
this change now results in a never ending collection of the subscription that is initialized every time the fragment view goes through the `onViewCreated()` resulting in multiple coroutines collecting. Needs to be moved to a custom view state container which utilizes a flow builder and `.stateIn()` extension function with WhileSubscribed in order to cancel sub when screen's lifecycle moves to the `onStop` event.

2021-09-02 17:30 UTC, 05nelsonm requested changes

2021-09-02 17:30 UTC, 05nelsonm commented on sphinx/screens-detail/subscription/subscription/src/main/java/chat/sphinx/subscription/ui/SubscriptionViewModel.kt
> +    )
remove.

not necessary.

2021-09-02 17:40 UTC, 05nelsonm approved these changes

2021-09-02 17:42 UTC, merged